services:
  - type: web
    name: ai-music-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: YOUTUBE_API_KEY
        value: AIzaSyDzRxmimKRwEGDPO2kC6NOtl2yPUnokeag 